export const QUERY_KEYS = Object.freeze({
  // User
  LIST_USER: 'LIST_USER',
  // role
  LIST_ROLE: 'LIST_ROLE',
  // permission
  LIST_PERMISSION: 'LIST_PERMISSION',
  // BRAND
  LIST_BRAND: 'LIST_BRAND',
  // PRODUCT
  LIST_PRODUCT: 'LIST_PRODUCT',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  // CATEGORY
  LIST_CATEGORY: 'LIST_CATEGORY',
  CATEGORY_TREE: 'CATEGORY_TREE',
  // CART
  CART: 'CART',
  CART_COUNT: 'CART_COUNT',
  // ORDER
  ORDER: 'ORDER',
  ORDER_ANALYTICS: 'ORDER_ANALYTICS',
  // ADDRESS
  ADDRESS_LIST: 'ADDRESS_LIST',
  // PAYMENT METHOD LIST
  PAYMENT_METHOD_LIST: 'PAYMENT_METHOD_LIST',
  // SHIPPING METHOD LIST
  SHIPPING_METHOD_LIST: 'SHIPPING_METHOD_LIST',
  // ACCOUNT
  PROFILE: 'PROFILE',
});
