export const QUERY_KEYS = Object.freeze({
  // User
  LIST_USER: 'LIST_USER',
  // role
  LIST_ROLE: 'LIST_ROLE',
  // permission
  LIST_PERMISSION: 'LIST_PERMISSION',
  // BRAND
  LIST_BRAND: 'LIST_BRAND',
  // PRODUCT
  LIST_PRODUCT: 'LIST_PRODUCT',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  // CATEGORY
  LIST_CATEGORY: 'LIST_CATEGORY',
  CATEGORY_TREE: 'CATEGORY_TREE',
  DETAIL_CATEGORY: 'DETAIL_CATEGORY',
  // CART
  CART: 'CART',
  CART_COUNT: 'CART_COUNT',
  // ORDER
  ORDER: 'ORDER',
  ORDER_LIST: 'ORDER_LIST',
  ORDER_ANALYTICS: 'ORDER_ANALYTICS',
  ORDER_STATISTICS: 'ORDER_STATISTICS',
  ORDER_HISTORY: 'ORDER_HISTORY',
  PAYMENT_STATUS: 'PAYMENT_STATUS',
  // ORDER WORKFLOW
  ORDER_WORKFLOW: 'ORDER_WORKFLOW',
  ORDER_WORKFLOW_ACTIONS: 'ORDER_WORKFLOW_ACTIONS',
  ORDER_LOGS: 'ORDER_LOGS',
  ORDER_TIMELINE: 'ORDER_TIMELINE',
  // ADDRESS
  ADDRESS_LIST: 'ADDRESS_LIST',
  // PAYMENT METHOD LIST
  PAYMENT_METHOD_LIST: 'PAYMENT_METHOD_LIST',
  // SHIPPING METHOD LIST
  SHIPPING_METHOD_LIST: 'SHIPPING_METHOD_LIST',
  // ACCOUNT
  PROFILE: 'PROFILE',
  // COUPON
  COUPON_AVAILABLE: 'COUPON_AVAILABLE',
  COUPON_MY_AVAILABLE: 'COUPON_MY_AVAILABLE',
  COUPON_LIST: 'COUPON_LIST',
  COUPON_DETAIL: 'COUPON_DETAIL',
  COUPON_VALIDATE: 'COUPON_VALIDATE',
  USER_COUPONS: 'USER_COUPONS',
});
