export const QUERY_KEYS = Object.freeze({
  // User
  LIST_USER: 'LIST_USER',
  // role
  LIST_ROLE: 'LIST_ROLE',
  // permission
  LIST_PERMISSION: 'LIST_PERMISSION',
  // BRAND
  LIST_BRAND: 'LIST_BRAND',
  // PRODUCT
  LIST_PRODUCT: 'LIST_PRODUCT',
  PRODUCT_DETAIL: 'PRODUCT_DETAIL',
  // CATEGORY
  LIST_CATEGORY: 'LIST_CATEGORY',
  CATEGORY_TREE: 'CATEGORY_TREE',
  // CART
  CART: 'CART',
  // ORDER
  ORDER: 'ORDER',
});
