import { Product } from '../../@types/product';

export const _products: Product[] = [
  {
    id: '1',
    cover:
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Modern Wooden Chair',
    price: 120,
    code: 'FURN001',
    sku: 'SKU-001',
    tags: ['Chair', 'Wood', 'Modern'],
    priceSale: 100,
    totalRating: 4.5,
    totalReview: 120,
    ratings: [
      { name: '5 Star', starCount: 80, reviewCount: 80 },
      { name: '4 Star', starCount: 30, reviewCount: 30 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r1',
        name: 'John Doe',
        avatarUrl: '/static/mock-images/avatars/avatar_1.jpg',
        comment: 'Very comfortable and stylish!',
        rating: 5,
        isPurchased: true,
        helpful: 10,
        postedAt: new Date(),
      },
    ],
    colors: ['#A0522D', '#FFFFFF'],
    status: 'sale',
    inventoryType: 'in_stock',
    sizes: ['Standard'],
    available: 50,
    description: 'A modern wooden chair perfect for any living room.',
    sold: 200,
    createdAt: new Date(),
    category: 'Chair',
    gender: 'Men',
  },
  {
    id: '2',
    cover:
      'https://images.unsplash.com/photo-1460518451285-97b6aa326961?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1460518451285-97b6aa326961?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Minimalist Sofa',
    price: 450,
    code: 'FURN002',
    sku: 'SKU-002',
    tags: ['Sofa', 'Minimalist', 'Living Room'],
    priceSale: 400,
    totalRating: 4.8,
    totalReview: 200,
    ratings: [
      { name: '5 Star', starCount: 150, reviewCount: 150 },
      { name: '4 Star', starCount: 40, reviewCount: 40 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r2',
        name: 'Jane Smith',
        avatarUrl: '/static/mock-images/avatars/avatar_2.jpg',
        comment: 'Looks great in my apartment!',
        rating: 5,
        isPurchased: true,
        helpful: 5,
        postedAt: new Date(),
      },
    ],
    colors: ['#808080', '#FFFFFF'],
    status: 'new',
    inventoryType: 'in_stock',
    sizes: ['2-Seater', '3-Seater'],
    available: 20,
    description: 'A minimalist sofa with a modern design.',
    sold: 120,
    createdAt: new Date(),
    category: 'Sofa',
    gender: 'Women',
  },
  {
    id: '3',
    cover:
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Scandinavian Coffee Table',
    price: 180,
    code: 'FURN003',
    sku: 'SKU-003',
    tags: ['Table', 'Coffee Table', 'Scandinavian'],
    priceSale: 150,
    totalRating: 4.7,
    totalReview: 300,
    ratings: [
      { name: '5 Star', starCount: 220, reviewCount: 220 },
      { name: '4 Star', starCount: 60, reviewCount: 60 },
      { name: '3 Star', starCount: 20, reviewCount: 20 },
    ],
    reviews: [
      {
        id: 'r3',
        name: 'Alice Johnson',
        avatarUrl: '/static/mock-images/avatars/avatar_3.jpg',
        comment: 'Perfect for my living room.',
        rating: 5,
        isPurchased: true,
        helpful: 8,
        postedAt: new Date(),
      },
    ],
    colors: ['#DEB887', '#FFFFFF'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['120x60cm'],
    available: 30,
    description: 'A Scandinavian style coffee table made from oak.',
    sold: 300,
    createdAt: new Date(),
    category: 'Table',
    gender: 'Men',
  },
  {
    id: '4',
    cover:
      'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Classic Bookshelf',
    price: 220,
    code: 'FURN004',
    sku: 'SKU-004',
    tags: ['Bookshelf', 'Classic', 'Wood'],
    priceSale: 200,
    totalRating: 4.3,
    totalReview: 80,
    ratings: [
      { name: '5 Star', starCount: 50, reviewCount: 50 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r4',
        name: 'Bob Lee',
        avatarUrl: '/static/mock-images/avatars/avatar_4.jpg',
        comment: 'Holds all my books easily.',
        rating: 4,
        isPurchased: true,
        helpful: 4,
        postedAt: new Date(),
      },
    ],
    colors: ['#8B4513', '#FFFFFF'],
    status: 'sale',
    inventoryType: 'in_stock',
    sizes: ['180x80x30cm'],
    available: 15,
    description: 'A classic bookshelf with ample storage.',
    sold: 90,
    createdAt: new Date(),
    category: 'Bookshelf',
    gender: 'Men',
  },
  {
    id: '5',
    cover:
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Elegant Dining Table',
    price: 600,
    code: 'FURN005',
    sku: 'SKU-005',
    tags: ['Dining Table', 'Elegant', 'Wood'],
    priceSale: 550,
    totalRating: 4.9,
    totalReview: 210,
    ratings: [
      { name: '5 Star', starCount: 180, reviewCount: 180 },
      { name: '4 Star', starCount: 25, reviewCount: 25 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r5',
        name: 'Chris Evans',
        avatarUrl: '/static/mock-images/avatars/avatar_5.jpg',
        comment: 'Perfect for family dinners.',
        rating: 5,
        isPurchased: true,
        helpful: 12,
        postedAt: new Date(),
      },
    ],
    colors: ['#A0522D', '#FFFFFF'],
    status: 'new',
    inventoryType: 'in_stock',
    sizes: ['200x90cm'],
    available: 10,
    description: 'An elegant dining table for six people.',
    sold: 150,
    createdAt: new Date(),
    category: 'Table',
    gender: 'Women',
  },
  {
    id: '6',
    cover:
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Comfy Armchair',
    price: 210,
    code: 'FURN006',
    sku: 'SKU-006',
    tags: ['Armchair', 'Comfy', 'Living Room'],
    priceSale: 180,
    totalRating: 4.1,
    totalReview: 60,
    ratings: [
      { name: '5 Star', starCount: 30, reviewCount: 30 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r6',
        name: 'Diana Prince',
        avatarUrl: '/static/mock-images/avatars/avatar_6.jpg',
        comment: 'So soft and cozy!',
        rating: 4,
        isPurchased: true,
        helpful: 3,
        postedAt: new Date(),
      },
    ],
    colors: ['#808080', '#A0522D'],
    status: '',
    inventoryType: 'low_stock',
    sizes: ['Standard'],
    available: 8,
    description: 'A comfy armchair for your reading nook.',
    sold: 60,
    createdAt: new Date(),
    category: 'Chair',
    gender: 'Women',
  },
  {
    id: '7',
    cover:
      'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1465101178521-c1a9136a3b99?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Industrial TV Stand',
    price: 320,
    code: 'FURN007',
    sku: 'SKU-007',
    tags: ['TV Stand', 'Industrial', 'Living Room'],
    priceSale: 300,
    totalRating: 4.6,
    totalReview: 110,
    ratings: [
      { name: '5 Star', starCount: 80, reviewCount: 80 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r7',
        name: 'Bruce Wayne',
        avatarUrl: '/static/mock-images/avatars/avatar_7.jpg',
        comment: 'Sturdy and stylish.',
        rating: 5,
        isPurchased: true,
        helpful: 7,
        postedAt: new Date(),
      },
    ],
    colors: ['#333333', '#A0522D'],
    status: 'sale',
    inventoryType: 'in_stock',
    sizes: ['150x40x50cm'],
    available: 15,
    description: 'Industrial style TV stand with metal frame.',
    sold: 70,
    createdAt: new Date(),
    category: 'TV Stand',
    gender: 'Men',
  },
  {
    id: '8',
    cover:
      'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Contemporary Bed Frame',
    price: 700,
    code: 'FURN008',
    sku: 'SKU-008',
    tags: ['Bed', 'Contemporary', 'Bedroom'],
    priceSale: 650,
    totalRating: 4.4,
    totalReview: 90,
    ratings: [
      { name: '5 Star', starCount: 60, reviewCount: 60 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r8',
        name: 'Clark Kent',
        avatarUrl: '/static/mock-images/avatars/avatar_8.jpg',
        comment: 'Solid and easy to assemble.',
        rating: 4,
        isPurchased: true,
        helpful: 5,
        postedAt: new Date(),
      },
    ],
    colors: ['#A0522D', '#FFFFFF'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['Queen', 'King'],
    available: 12,
    description: 'A contemporary bed frame for modern bedrooms.',
    sold: 55,
    createdAt: new Date(),
    category: 'Bed',
    gender: 'Women',
  },
  {
    id: '9',
    cover:
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1505691938895-1758d7feb511?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Rustic Nightstand',
    price: 90,
    code: 'FURN009',
    sku: 'SKU-009',
    tags: ['Nightstand', 'Rustic', 'Bedroom'],
    priceSale: 80,
    totalRating: 4.2,
    totalReview: 70,
    ratings: [
      { name: '5 Star', starCount: 40, reviewCount: 40 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r9',
        name: 'Barry Allen',
        avatarUrl: '/static/mock-images/avatars/avatar_9.jpg',
        comment: 'Perfect for my bedside lamp.',
        rating: 4,
        isPurchased: true,
        helpful: 2,
        postedAt: new Date(),
      },
    ],
    colors: ['#8B4513', '#FFFFFF'],
    status: 'new',
    inventoryType: 'in_stock',
    sizes: ['Standard'],
    available: 20,
    description: 'A rustic nightstand with drawer.',
    sold: 40,
    createdAt: new Date(),
    category: 'Nightstand',
    gender: 'Men',
  },
  {
    id: '10',
    cover:
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Vintage Dresser',
    price: 350,
    code: 'FURN010',
    sku: 'SKU-010',
    tags: ['Dresser', 'Vintage', 'Bedroom'],
    priceSale: 320,
    totalRating: 4.8,
    totalReview: 130,
    ratings: [
      { name: '5 Star', starCount: 100, reviewCount: 100 },
      { name: '4 Star', starCount: 25, reviewCount: 25 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r10',
        name: 'Peter Parker',
        avatarUrl: '/static/mock-images/avatars/avatar_10.jpg',
        comment: 'Lots of storage space.',
        rating: 5,
        isPurchased: true,
        helpful: 6,
        postedAt: new Date(),
      },
    ],
    colors: ['#DEB887', '#FFFFFF'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['120x50x80cm'],
    available: 18,
    description: 'A vintage dresser with six drawers.',
    sold: 80,
    createdAt: new Date(),
    category: 'Dresser',
    gender: 'Women',
  },
  {
    id: '11',
    cover:
      'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Modern Wardrobe',
    price: 800,
    code: 'FURN011',
    sku: 'SKU-011',
    tags: ['Wardrobe', 'Modern', 'Bedroom'],
    priceSale: 750,
    totalRating: 4.0,
    totalReview: 50,
    ratings: [
      { name: '5 Star', starCount: 20, reviewCount: 20 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r11',
        name: 'Steve Rogers',
        avatarUrl: '/static/mock-images/avatars/avatar_11.jpg',
        comment: 'Spacious and modern.',
        rating: 4,
        isPurchased: true,
        helpful: 2,
        postedAt: new Date(),
      },
    ],
    colors: ['#808080', '#FFFFFF'],
    status: '',
    inventoryType: 'low_stock',
    sizes: ['200x60x220cm'],
    available: 6,
    description: 'A modern wardrobe with sliding doors.',
    sold: 30,
    createdAt: new Date(),
    category: 'Wardrobe',
    gender: 'Men',
  },
  {
    id: '12',
    cover:
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Round Dining Table',
    price: 400,
    code: 'FURN012',
    sku: 'SKU-012',
    tags: ['Dining Table', 'Round', 'Wood'],
    priceSale: 370,
    totalRating: 4.5,
    totalReview: 75,
    ratings: [
      { name: '5 Star', starCount: 50, reviewCount: 50 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r12',
        name: 'Natasha Romanoff',
        avatarUrl: '/static/mock-images/avatars/avatar_12.jpg',
        comment: 'Great for small spaces.',
        rating: 5,
        isPurchased: true,
        helpful: 4,
        postedAt: new Date(),
      },
    ],
    colors: ['#A0522D', '#FFFFFF'],
    status: 'sale',
    inventoryType: 'in_stock',
    sizes: ['120cm'],
    available: 14,
    description: 'A round dining table for four people.',
    sold: 45,
    createdAt: new Date(),
    category: 'Table',
    gender: 'Women',
  },
  {
    id: '13',
    cover:
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Classic Rocking Chair',
    price: 160,
    code: 'FURN013',
    sku: 'SKU-013',
    tags: ['Chair', 'Rocking', 'Classic'],
    priceSale: 140,
    totalRating: 4.7,
    totalReview: 60,
    ratings: [
      { name: '5 Star', starCount: 45, reviewCount: 45 },
      { name: '4 Star', starCount: 10, reviewCount: 10 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r13',
        name: 'Tony Stark',
        avatarUrl: '/static/mock-images/avatars/avatar_13.jpg',
        comment: 'Very relaxing.',
        rating: 5,
        isPurchased: true,
        helpful: 3,
        postedAt: new Date(),
      },
    ],
    colors: ['#8B4513', '#FFFFFF'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['Standard'],
    available: 22,
    description: 'A classic wooden rocking chair.',
    sold: 35,
    createdAt: new Date(),
    category: 'Chair',
    gender: 'Men',
  },
  {
    id: '14',
    cover:
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Glass Top Coffee Table',
    price: 250,
    code: 'FURN014',
    sku: 'SKU-014',
    tags: ['Table', 'Glass', 'Coffee Table'],
    priceSale: 230,
    totalRating: 4.3,
    totalReview: 40,
    ratings: [
      { name: '5 Star', starCount: 25, reviewCount: 25 },
      { name: '4 Star', starCount: 10, reviewCount: 10 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r14',
        name: 'Wanda Maximoff',
        avatarUrl: '/static/mock-images/avatars/avatar_14.jpg',
        comment: 'Looks elegant.',
        rating: 4,
        isPurchased: true,
        helpful: 2,
        postedAt: new Date(),
      },
    ],
    colors: ['#FFFFFF', '#A0522D'],
    status: 'new',
    inventoryType: 'in_stock',
    sizes: ['110x60cm'],
    available: 20,
    description: 'A coffee table with a glass top and wooden legs.',
    sold: 25,
    createdAt: new Date(),
    category: 'Table',
    gender: 'Women',
  },
  {
    id: '15',
    cover:
      'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Upholstered Bench',
    price: 180,
    code: 'FURN015',
    sku: 'SKU-015',
    tags: ['Bench', 'Upholstered', 'Entryway'],
    priceSale: 160,
    totalRating: 4.6,
    totalReview: 55,
    ratings: [
      { name: '5 Star', starCount: 40, reviewCount: 40 },
      { name: '4 Star', starCount: 10, reviewCount: 10 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r15',
        name: 'Scott Lang',
        avatarUrl: '/static/mock-images/avatars/avatar_15.jpg',
        comment: 'Great for my hallway.',
        rating: 5,
        isPurchased: true,
        helpful: 2,
        postedAt: new Date(),
      },
    ],
    colors: ['#808080', '#FFFFFF'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['120x40cm'],
    available: 17,
    description: 'A comfortable upholstered bench for entryways.',
    sold: 28,
    createdAt: new Date(),
    category: 'Bench',
    gender: 'Men',
  },
  {
    id: '16',
    cover:
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Floating Wall Shelf',
    price: 60,
    code: 'FURN016',
    sku: 'SKU-016',
    tags: ['Shelf', 'Wall', 'Floating'],
    priceSale: 50,
    totalRating: 4.2,
    totalReview: 35,
    ratings: [
      { name: '5 Star', starCount: 20, reviewCount: 20 },
      { name: '4 Star', starCount: 10, reviewCount: 10 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r16',
        name: 'Sam Wilson',
        avatarUrl: '/static/mock-images/avatars/avatar_16.jpg',
        comment: 'Easy to install.',
        rating: 4,
        isPurchased: true,
        helpful: 1,
        postedAt: new Date(),
      },
    ],
    colors: ['#A0522D', '#FFFFFF'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['80x20cm'],
    available: 40,
    description: 'A floating wall shelf for books and decor.',
    sold: 60,
    createdAt: new Date(),
    category: 'Shelf',
    gender: 'Men',
  },
  {
    id: '17',
    cover:
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Mid-century Sideboard',
    price: 500,
    code: 'FURN017',
    sku: 'SKU-017',
    tags: ['Sideboard', 'Mid-century', 'Storage'],
    priceSale: 470,
    totalRating: 4.5,
    totalReview: 45,
    ratings: [
      { name: '5 Star', starCount: 30, reviewCount: 30 },
      { name: '4 Star', starCount: 10, reviewCount: 10 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r17',
        name: 'Hope Van Dyne',
        avatarUrl: '/static/mock-images/avatars/avatar_17.jpg',
        comment: 'Beautiful and functional.',
        rating: 5,
        isPurchased: true,
        helpful: 2,
        postedAt: new Date(),
      },
    ],
    colors: ['#DEB887', '#A0522D'],
    status: 'sale',
    inventoryType: 'in_stock',
    sizes: ['160x45x75cm'],
    available: 18,
    description: 'A mid-century modern sideboard for storage.',
    sold: 32,
    createdAt: new Date(),
    category: 'Sideboard',
    gender: 'Women',
  },
  {
    id: '18',
    cover:
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1519985176271-adb1088fa94c?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Kids Study Desk',
    price: 130,
    code: 'FURN018',
    sku: 'SKU-018',
    tags: ['Desk', 'Kids', 'Study'],
    priceSale: 120,
    totalRating: 4.8,
    totalReview: 160,
    ratings: [
      { name: '5 Star', starCount: 120, reviewCount: 120 },
      { name: '4 Star', starCount: 30, reviewCount: 30 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r18',
        name: 'Nick Fury',
        avatarUrl: '/static/mock-images/avatars/avatar_18.jpg',
        comment: 'Perfect for my kids.',
        rating: 5,
        isPurchased: true,
        helpful: 8,
        postedAt: new Date(),
      },
    ],
    colors: ['#FFFFFF', '#A0522D'],
    status: 'new',
    inventoryType: 'in_stock',
    sizes: ['100x60cm'],
    available: 35,
    description: 'A study desk designed for kids.',
    sold: 90,
    createdAt: new Date(),
    category: 'Desk',
    gender: 'Men',
  },
  {
    id: '19',
    cover:
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Outdoor Patio Set',
    price: 650,
    code: 'FURN019',
    sku: 'SKU-019',
    tags: ['Patio', 'Outdoor', 'Set'],
    priceSale: 600,
    totalRating: 4.1,
    totalReview: 25,
    ratings: [
      { name: '5 Star', starCount: 10, reviewCount: 10 },
      { name: '4 Star', starCount: 10, reviewCount: 10 },
      { name: '3 Star', starCount: 5, reviewCount: 5 },
    ],
    reviews: [
      {
        id: 'r19',
        name: 'Maria Hill',
        avatarUrl: '/static/mock-images/avatars/avatar_19.jpg',
        comment: 'Great for summer evenings.',
        rating: 4,
        isPurchased: true,
        helpful: 1,
        postedAt: new Date(),
      },
    ],
    colors: ['#A0522D', '#FFFFFF'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['4-Seater'],
    available: 30,
    description: 'A complete patio set for outdoor relaxation.',
    sold: 20,
    createdAt: new Date(),
    category: 'Patio',
    gender: 'Women',
  },
  {
    id: '20',
    cover:
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=600&q=80',
      'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=600&q=80',
    ],
    name: 'Lounge Recliner',
    price: 350,
    code: 'FURN020',
    sku: 'SKU-020',
    tags: ['Recliner', 'Lounge', 'Living Room'],
    priceSale: 320,
    totalRating: 4.4,
    totalReview: 70,
    ratings: [
      { name: '5 Star', starCount: 40, reviewCount: 40 },
      { name: '4 Star', starCount: 20, reviewCount: 20 },
      { name: '3 Star', starCount: 10, reviewCount: 10 },
    ],
    reviews: [
      {
        id: 'r20',
        name: 'Stephen Strange',
        avatarUrl: '/static/mock-images/avatars/avatar_20.jpg',
        comment: 'Very relaxing after a long day.',
        rating: 5,
        isPurchased: true,
        helpful: 3,
        postedAt: new Date(),
      },
    ],
    colors: ['#808080', '#A0522D'],
    status: '',
    inventoryType: 'in_stock',
    sizes: ['Standard'],
    available: 16,
    description: 'A lounge recliner for ultimate comfort.',
    sold: 38,
    createdAt: new Date(),
    category: 'Recliner',
    gender: 'Men',
  },
];
